In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
491,492,0,3,"Windelov, Mr. Einar",male,21.0,0,0,SOTON/OQ 3101317,7.2500,NaN,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
81,82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29.0,0,0,345779,9.5000,NaN,S
411,412,0,3,"Hart, Mr. Henry",male,NaN,0,0,394140,6.8583,NaN,Q
748,749,0,1,"Marvin, Mr. Daniel Warner",male,19.0,1,0,113773,53.1000,D30,S
514,515,0,3,"Coleff, Mr. Satio",male,24.0,0,0,349209,7.4958,NaN,S
668,669,0,3,"Cook, Mr. Jacob",male,43.0,0,0,A/5 3536,8.0500,NaN,S
817,818,0,2,"Mallet, Mr. Albert",male,31.0,1,1,S.C./PARIS 2079,37.0042,NaN,C

In [4]:
!pip install pandas-profiling

Requirement already satisfied: pandas-profiling in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (3.6.6)
Requirement already satisfied: ydata-profiling in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from pandas-profiling) (4.9.0)
Requirement already satisfied: requests<3,>=2.24.0 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (2.28.1)
Requirement already satisfied: pydantic>=2 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (2.8.2)
Requirement already satisfied: imagehash==4.3.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (4.3.1)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (3.1.2)
Requirement already satisfied: numpy<2,>=1.16.0 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (1.23.5)
Requirement already satisfied: wordcloud>=1.9.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (1.9.2)
Requirement already satisfied: matplotlib<3.10,>=3.5 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (3.7.1)
Requirement already satisfied: scipy<1.14,>=1.4.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (1.10.1)
Requirement already satisfied: tqdm<5,>=4.48.2 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (4.66.1)
Requirement already satisfied: phik<0.13,>=0.11.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (0.12.4)
Requirement already satisfied: typeguard<5,>=3 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (4.3.0)
Requirement already satisfied: dacite>=1.8 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (1.8.1)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (1.12)
Requirement already satisfied: pandas!=1.4.0,<3,>1.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (2.0.0)
Requirement already satisfied: visions[type_image_path]<0.7.7,>=0.7.5 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (0.7.6)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (0.14.2)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (0.12.2)
Requirement already satisfied: htmlmin==0.1.12 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (0.1.12)
Requirement already satisfied: numba<1,>=0.56.0 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from ydata-profiling->pandas-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (1.7.0)
Requirement already satisfied: pillow in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling->pandas-profiling) (2.1.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling->pandas-profiling) (4.39.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling->pandas-profiling) (1.0.7)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling->pandas-profiling) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling->pandas-profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling->pandas-profiling) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling->pandas-profiling) (3.0.9)
Requirement already satisfied: cycler>=0.10 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling->pandas-profiling) (0.11.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from numba<1,>=0.56.0->ydata-profiling->pandas-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling->pandas-profiling) (2022.7)
Requirement already satisfied: tzdata>=2022.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling->pandas-profiling) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from phik<0.13,>=0.11.1->ydata-profiling->pandas-profiling) (1.2.0)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from pydantic>=2->ydata-profiling->pandas-profiling) (4.12.2)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from pydantic>=2->ydata-profiling->pandas-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from pydantic>=2->ydata-profiling->pandas-profiling) (2.20.1)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2023.7.22)
Requirement already satisfied: idna<4,>=2.5 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (3.4)
Requirement already satisfied: patsy>=0.5.6 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (0.5.6)
Requirement already satisfied: colorama in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from tqdm<5,>=4.48.2->ydata-profiling->pandas-profiling) (0.4.6)
Requirement already satisfied: networkx>=2.4 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling->pandas-profiling) (3.3)
Requirement already satisfied: attrs>=19.3.0 in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling->pandas-profiling) (22.1.0)
Requirement already satisfied: six in c:\users\91906\anaconda3\envs\opencv\lib\site-packages (from patsy>=0.5.6->statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (1.16.0)